spring.application.name=autowashpro
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AutoWashProDB;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=12345

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8081


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

payos.client-id=9ca89c8f-4048-4a53-ad27-d45850a5f705
payos.api-key=6d0ebb03-8073-4c6b-90dd-33d3593d12bb
payos.checksum-key=1289a6af30332ae9b008dd5c79a1339de19847299845feed92fa8b9d79b0afb1
payos.return-url=http://localhost:5173/payment/success
payos.cancel-url=http://localhost:5173/payment/cancel

# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=audelabooking@gmail.com
spring.mail.password=jtdv cosw iriw ygpd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URL
app.base-url=http://localhost:5173